services:
  insurgency-sandstorm-server:
    image: rouhim/insurgency-sandstorm-server
    build:
      context: container-data
      dockerfile: Containerfile
    restart: unless-stopped
    environment:
      FAST_BOOT: "false"
    volumes:
      - "./data:/data"
    ports:
      - "0.0.0.0:27102:27102/udp"
      - "0.0.0.0:27102:27102/tcp"
      - "0.0.0.0:27131:27131/udp"
      - "0.0.0.0:27131:27131/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"