services:
  insurgency-sandstorm-server:
    image: rouhim/insurgency-sandstorm-server
    build:
      context: container-data
      dockerfile: Containerfile
    restart: unless-stopped
    environment:
      FAST_BOOT: "false"
      SERVER_NAME: "My Server"
      MAP: "Oilfield"
      SCENARIO: "Scenario_Refinery_Push_Security"
      MAX_PLAYERS: "28"
    volumes:
      - "./data:/data"
    ports:
      - "27102:27102/udp"
      - "27102:27102/tcp"
      - "27131:27131/udp"
      - "27131:27131/tcp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"