FROM rouhim/steamcmd:latest
USER $USER

ENV STEAM_APP_ID "581330"
ENV STARTUP_COMMAND 'Insurgency/Binaries/Linux/InsurgencyServer-Linux-Shipping $MAP?Scenario=$SCENARIO?MaxPlayers=$MAX_PLAYERS -Port=27102 -QueryPort=27131 -log -hostname="$SERVER_NAME"'

# expose game and query port
EXPOSE 27102/tcp \
       27102/udp \
       27131/tcp \
       27131/udp

COPY pre.sh $USER_HOME/pre.sh